Document: libattachsql
Title: Debian libattachsql Manual
Author: <insert document author here>
Abstract: This manual describes what libattachsql is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libattachsql/libattachsql.sgml.gz

Format: postscript
Files: /usr/share/doc/libattachsql/libattachsql.ps.gz

Format: text
Files: /usr/share/doc/libattachsql/libattachsql.text.gz

Format: HTML
Index: /usr/share/doc/libattachsql/html/index.html
Files: /usr/share/doc/libattachsql/html/*.html
